import { StyleSheet } from 'react-native';
import { Typography, Spacing } from '@/constants/theme';

export const styles = StyleSheet.create({
  toastContainer: {
    position: 'absolute',
    bottom: 30,
    left: 20,
    right: 20,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 5,
    zIndex: 9999,
  },
  toastText: {
    color: '#FFF',
    fontSize: 14,
    fontFamily: Typography.uiBold,
    textAlign: 'center',
  },
  container: {
    flex: 1,
    paddingTop: 60,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: Spacing.three,
    marginBottom: Spacing.three,
  },
  greetingText: {
    fontSize: 14,
    fontFamily: Typography.body,
    opacity: 0.8,
  },
  userName: {
    fontSize: 22,
    fontFamily: Typography.uiBold,
    marginTop: 2,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
  },
  logoutBtn: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 18,
    borderWidth: 1,
  },
  scrollContent: {
    paddingHorizontal: Spacing.three,
    paddingBottom: 80,
  },
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: Spacing.three,
  },
  statCard: {
    flex: 0.48,
    borderRadius: 16,
    padding: Spacing.three,
    shadowColor: '#000',
    shadowOpacity: 0.02,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 1,
  },
  statIconContainer: {
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: Spacing.two,
  },
  statLabel: {
    fontSize: 12,
    fontFamily: Typography.bodyMedium,
  },
  statValue: {
    fontSize: 22,
    fontFamily: Typography.uiBold,
    marginVertical: 4,
  },
  statSubtitle: {
    fontSize: 10,
    fontFamily: Typography.body,
  },
  pendingAlertBanner: {
    borderRadius: 14,
    padding: Spacing.three,
    marginBottom: Spacing.three,
  },
  alertContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  alertCircle: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#FFF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  alertTitle: {
    fontSize: 14,
    fontFamily: Typography.uiBold,
  },
  alertDesc: {
    fontSize: 12,
    fontFamily: Typography.body,
    marginTop: 1,
  },
  clipboardBanner: {
    borderWidth: 1,
    borderRadius: 14,
    padding: Spacing.three,
    marginBottom: Spacing.three,
  },
  clipboardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  clipboardTitle: {
    fontSize: 14,
    fontFamily: Typography.uiBold,
  },
  clipboardDesc: {
    fontSize: 13,
    fontFamily: Typography.body,
    marginBottom: 12,
  },
  clipboardActions: {
    flexDirection: 'row',
  },
  clipBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    marginRight: 8,
  },
  clipBtnText: {
    color: '#FFF',
    fontSize: 12,
    fontWeight: 'bold',
  },
  clipBtnCancel: {
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    justifyContent: 'center',
  },
  clipBtnCancelText: {
    fontSize: 12,
    fontWeight: 'bold',
  },
  expandableBox: {
    borderRadius: 14,
    paddingHorizontal: Spacing.three,
    paddingVertical: Spacing.three,
    marginBottom: Spacing.three,
    shadowColor: '#000',
    shadowOpacity: 0.01,
    shadowRadius: 4,
    elevation: 1,
  },
  expandableHeader: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  expandableTitle: {
    flex: 1,
    marginLeft: 10,
    fontSize: 14,
    fontFamily: Typography.uiBold,
  },
  expandableBody: {
    marginTop: 14,
  },
  textInput: {
    borderWidth: 1,
    borderRadius: 10,
    padding: 10,
    fontSize: 13,
    fontFamily: Typography.body,
    textAlignVertical: 'top',
    marginBottom: 10,
  },
  submitButton: {
    height: 40,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  submitButtonText: {
    color: '#FFF',
    fontWeight: 'bold',
    fontSize: 14,
  },
  guideText: {
    fontSize: 12,
    lineHeight: 18,
    marginBottom: 10,
  },
  stepBox: {
    marginBottom: 10,
  },
  stepTitle: {
    fontSize: 11,
    fontFamily: Typography.uiBold,
    textTransform: 'uppercase',
    marginBottom: 2,
  },
  stepDetail: {
    fontSize: 12,
    opacity: 0.8,
  },
  codeBlock: {
    backgroundColor: '#0000000d',
    padding: 8,
    borderRadius: 6,
    marginTop: 4,
  },
  codeText: {
    fontFamily: Typography.mono,
    fontSize: 10,
    color: '#333',
  },
  tokenContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 8,
    height: 38,
    marginTop: 4,
  },
  tokenInput: {
    flex: 1,
    fontFamily: Typography.mono,
    fontSize: 11,
  },
  tabsContainer: {
    flexDirection: 'row',
    marginBottom: Spacing.three,
  },
  tabItem: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    marginRight: 8,
    backgroundColor: '#00000008',
  },
  tabText: {
    fontSize: 12,
    fontWeight: 'bold',
  },
  emptyContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 50,
  },
  emptyText: {
    fontSize: 16,
    fontFamily: Typography.uiBold,
    marginTop: 12,
  },
  emptySub: {
    fontSize: 12,
    marginTop: 4,
  },
  draftCard: {
    borderRadius: 14,
    padding: Spacing.three,
    marginBottom: Spacing.two,
    shadowColor: '#000',
    shadowOpacity: 0.01,
    shadowRadius: 4,
    elevation: 1,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  avatarPlaceholder: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cardMeta: {
    flex: 1,
    marginLeft: 12,
  },
  merchantName: {
    fontSize: 15,
    fontFamily: Typography.uiBold,
  },
  draftDate: {
    fontSize: 11,
    fontFamily: Typography.body,
    marginTop: 2,
  },
  amountText: {
    fontSize: 16,
    fontFamily: Typography.uiBold,
  },
  badge: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
    marginTop: 4,
  },
  badgeText: {
    fontSize: 9,
    fontWeight: 'bold',
    textTransform: 'uppercase',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: Spacing.four,
    maxHeight: '85%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Spacing.three,
  },
  modalTitle: {
    fontSize: 20,
  },
  closeBtn: {
    padding: 4,
  },
  rawMsgContainer: {
    borderWidth: 1,
    borderRadius: 12,
    padding: Spacing.three,
    marginBottom: Spacing.three,
  },
  rawMsgHeader: {
    fontSize: 10,
    fontFamily: Typography.uiBold,
    marginBottom: 4,
  },
  rawMsgText: {
    fontSize: 12,
    lineHeight: 18,
    fontStyle: 'italic',
  },
  formGroup: {
    marginBottom: Spacing.three,
  },
  inputLabel: {
    fontSize: 12,
    fontFamily: Typography.uiBold,
    marginBottom: 6,
  },
  formInput: {
    height: 44,
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 12,
    fontSize: 14,
    fontFamily: Typography.body,
  },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: Spacing.two,
  },
  actionBtn: {
    flex: 0.48,
    height: 48,
    borderRadius: 12,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  actionBtnText: {
    color: '#FFF',
    fontSize: 14,
    fontWeight: 'bold',
  },
});
